<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Article;

class AIEnhancedArticleSeeder extends Seeder
{
    public function run()
    {
        $articles = [
            [
                'title' => 'Panduan Lengkap Memilih Produk Halal untuk Keluarga',
                'slug' => 'panduan-lengkap-memilih-produk-halal-keluarga',
                'excerpt' => 'Pelajari cara memilih produk halal yang aman dan berkualitas untuk konsumsi sehari-hari keluarga Anda.',
                'content' => '<h2>Mengenal Label Halal di Indonesia</h2><p>Label halal adalah tanda yang menunjukkan bahwa suatu produk telah melalui proses sertifikasi halal oleh lembaga yang berwenang seperti MUI (Majelis Ulama Indonesia) dan BPJPH. Memilih produk halal bukan hanya sekadar mengikuti syariat, tetapi juga memastikan bahwa produk yang dikonsumsi oleh keluarga Anda adalah produk yang <i>thayyib</i> (baik dan aman).</p><h3>Pentingnya Sertifikasi Halal</h3><p>Sertifikasi halal menjamin bahwa seluruh rantai produksi, mulai dari bahan baku, proses pengolahan, hingga distribusi, bebas dari zat-zat yang diharamkan. Ini memberikan ketenangan pikiran bagi konsumen muslim di tengah maraknya produk impor dan produk olahan modern yang kompleks kandungannya.</p><h3>Cara Memeriksa Logo Halal yang Benar</h3><ul><li><strong>Periksa Keaslian Logo:</strong> Pastikan logo halal memiliki nomor registrasi yang valid. Anda bisa melakukan pengecekan melalui website resmi BPJPH atau MUI.</li><li><strong>Gunakan Aplikasi Halalytics:</strong> Dengan fitur scan barcode kami, Anda bisa mendapatkan informasi instan mengenai status halal produk yang terintegrasi dengan database resmi.</li><li><strong>Cek Tanggal Kadaluarsa:</strong> Produk halal yang sudah kadaluarsa kehilangan aspek <i>thayyib</i>-nya.</li></ul><h2>Memahami Titik Kritis Kehalalan</h2><p>Titik kritis adalah tahapan dalam proses produksi di mana kemungkinan terjadinya kontaminasi bahan haram sangat besar. Beberapa bahan yang sering menjadi titik kritis antara lain:</p><ul><li><strong>Daging:</strong> Harus dipastikan disembelih sesuai syariat Islam.</li><li><strong>Gelatin:</strong> Sering ditemukan pada permen dan produk susu, pastikan bukan berasal dari babi.</li><li><strong>Flavor dan Pewarna:</strong> Seringkali menggunakan pelarut atau media yang tidak halal.</li></ul><h3>Tips Belanja Cerdas untuk Keluarga</h3><ol><li>Selalu buat daftar belanjaan dan utamakan produk yang sudah dikenal status halalnya.</li><li>Baca label komposisi dengan teliti, waspadai kode E-numbers yang meragukan.</li><li>Edukasi anggota keluarga, terutama anak-anak, untuk mengenali simbol halal sejak dini.</li></ol><p>Dengan pemahaman yang baik, kita dapat menjaga kesehatan fisik dan spiritual keluarga melalui konsumsi produk yang jelas kehalalannya. Halalytics hadir untuk menjadi teman setia Anda dalam perjalanan hidup halal yang lebih mudah dan modern.</p>',
                'ai_summary' => 'Artikel ini memberikan panduan komprehensif tentang cara memilih produk halal untuk keluarga, termasuk pengenalan label halal, pemahaman titik kritis, dan tips praktis belanja cerdas.',
                'image' => 'https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=1200',
                'category' => 'Panduan Halal',
                'source' => 'Internal',
                'author' => 'Tim Pakar Halalytics',
                'is_published' => true,
                'status' => 'published',
                'views' => 1250,
            ],
            [
                'title' => 'Bahaya Bahan Pengawet dalam Makanan Olahan',
                'slug' => 'bahaya-bahan-pengawet-makanan-olahan',
                'excerpt' => 'Pelajari tentang berbagai jenis bahan pengawet yang umum digunakan dalam makanan olahan dan potensi risikonya.',
                'content' => '<h2>Jenis Bahan Pengawet</h2><p>Bahan pengawet adalah zat yang ditambahkan ke makanan untuk mencegah pertumbuhan bakteri dan memperpanjang umur simpan.</p><h3>Bahan Pengawet Umum</h3><ul><li>Natrium Benzoat (E211) - Aman dalam jumlah terbatas</li><li>Kalium Sorbat (E202) - Efektif melawan jamur</li><li>Natrium Nitrit (E250) - Digunakan dalam daging olahan</li></ul><h2>Risiko Kesehatan</h2><p>Beberapa bahan pengawet dapat menyebabkan alergi, masalah pencernaan, dan dalam jangka panjang dapat meningkatkan risiko kanker.</p>',
                'ai_summary' => 'Artikel ini membahas bahaya bahan pengawet dalam makanan olahan, jenis-jenisnya, dan risiko kesehatan yang mungkin timbul.',
                'image' => 'https://images.tokopedia.net/img/cache/700/VqbcmM/2024/1/2/preservatives-danger.jpg',
                'category' => 'Kesehatan',
                'source' => 'Internal',
                'author' => 'Dr. Halal Expert',
                'is_published' => true,
                'status' => 'published',
                'views' => 890,
            ],
            [
                'title' => 'Kosmetik Halal: Tren Baru dalam Industri Kecantikan',
                'slug' => 'kosmetik-halal-tren-baru-industri-kecantikan',
                'excerpt' => 'Eksplorasi dunia kosmetik halal yang semakin populer di kalangan muslimah modern.',
                'content' => '<h2>Apa Itu Kosmetik Halal?</h2><p>Kosmetik halal adalah produk perawatan tubuh yang bahan-bahannya tidak mengandung zat haram dan proses produksinya sesuai syariat Islam.</p><h3>Standar Halal Kosmetik</h3><ul><li>Tidak mengandung alkohol</li><li>Tidak menggunakan bahan dari hewan haram</li><li>Proses produksi terpisah dari produk non-halal</li></ul><h2>Manfaat Kosmetik Halal</h2><p>Selain sesuai syariat, kosmetik halal juga cenderung lebih aman karena menggunakan bahan-bahan alami dan bebas dari zat berbahaya.</p>',
                'ai_summary' => 'Artikel ini mengupas tren kosmetik halal yang sedang berkembang, definisi, standar, dan manfaatnya bagi konsumen muslim.',
                'image' => 'https://images.tokopedia.net/img/cache/700/VqbcmM/2024/1/3/halal-cosmetics.jpg',
                'category' => 'Kosmetik',
                'source' => 'Internal',
                'author' => 'Beauty Expert',
                'is_published' => true,
                'status' => 'published',
                'views' => 1450,
            ],
            [
                'title' => 'Mengenal Bahan Tambahan Pangan (BTP) dalam Makanan',
                'slug' => 'mengenal-bahan-tambahan-pangan-btp-makanan',
                'excerpt' => 'Panduan lengkap memahami kode BTP dan fungsinya dalam industri makanan modern.',
                'content' => '<h2>Apa Itu BTP?</h2><p>Bahan Tambahan Pangan (BTP) adalah bahan yang ditambahkan ke makanan untuk tujuan tertentu seperti pengawet, pewarna, atau penyedap.</p><h3>Kode BTP Umum</h3><ul><li>E100-E199: Pewarna</li><li>E200-E299: Pengawet</li><li>E300-E399: Antioksidan</li><li>E400-E499: Emulsifier</li></ul><h2>Klasifikasi BTP</h2><p>BTP diklasifikasikan berdasarkan fungsi dan keamanannya. Beberapa BTP alami, lainnya sintetis, namun semuanya telah melalui uji keamanan BPOM.</p>',
                'ai_summary' => 'Artikel ini menjelaskan tentang Bahan Tambahan Pangan (BTP), kode-kodenya, klasifikasi, dan pentingnya pemahaman konsumen.',
                'image' => 'https://images.tokopedia.net/img/cache/700/VqbcmM/2024/1/4/food-additives.jpg',
                'category' => 'Edukasi',
                'source' => 'Internal',
                'author' => 'Food Scientist',
                'is_published' => true,
                'status' => 'published',
                'views' => 720,
            ],
            [
                'title' => 'Panduan Aman Menggunakan Suplemen Kesehatan',
                'slug' => 'panduan-aman-menggunakan-suplement-kesehatan',
                'excerpt' => 'Tips penting sebelum mengonsumsi suplemen kesehatan untuk menjaga kebugaran tubuh.',
                'content' => '<h2>Jenis Suplemen Kesehatan</h2><p>Suplemen kesehatan meliputi vitamin, mineral, herbal, dan nutrisi lainnya yang mendukung fungsi tubuh.</p><h3>Tips Aman Menggunakan Suplemen</h3><ul><li>Konsultasi dengan dokter</li><li>Pilih produk berlabel halal</li><li>Perhatikan dosis yang direkomendasikan</li><li>Cek tanggal kadaluarsa</li></ul><h2>Risiko Overdosis</h2><p>Beberapa vitamin seperti A, D, E, K yang larut dalam lemak dapat menimbulkan toksisitas jika dikonsumsi berlebihan.</p>',
                'ai_summary' => 'Artikel ini memberikan panduan aman menggunakan suplemen kesehatan, jenis-jenisnya, tips penggunaan, dan risiko overdosis.',
                'image' => 'https://images.tokopedia.net/img/cache/700/VqbcmM/2024/1/5/health-supplements.jpg',
                'category' => 'Kesehatan',
                'source' => 'Internal',
                'author' => 'Nutritionist',
                'is_published' => true,
                'status' => 'published',
                'views' => 980,
            ],
            [
                'title' => 'Makanan untuk Ibu Menyusui: Nutrisi yang Dibutuhkan',
                'slug' => 'makanan-ibu-menyusui-nutrisi-dibutuhkan',
                'excerpt' => 'Panduan nutrisi penting untuk ibu menyusui agar ASI berkualitas dan bayi sehat.',
                'content' => '<h2>Nutrisi Utama Ibu Menyusui</h2><p>Ibu menyusui membutuhkan asupan nutrisi lebih tinggi untuk memproduksi ASI yang berkualitas.</p><h3>Nutrisi Penting</h3><ul><li>Protein: 71g per hari</li><li>Kalsium: 1000mg per hari</li><li>Zat Besi: 9mg per hari</li><li>Vitamin D: 15mcg per hari</li></ul><h2>Makanan Rekomendasi</h2><p>Konsumsi sayuran hijau, kacang-kacangan, ikan, susu, dan buah-buahan untuk memenuhi kebutuhan nutrisi harian.</p>',
                'ai_summary' => 'Artikel ini membahas nutrisi penting untuk ibu menyusui, kebutuhan harian, dan rekomendasi makanan yang sehat.',
                'image' => 'https://images.tokopedia.net/img/cache/700/VqbcmM/2024/1/6/breastfeeding-nutrition.jpg',
                'category' => 'Kesehatan Ibu & Anak',
                'source' => 'Internal',
                'author' => 'Pediatric Nutritionist',
                'is_published' => true,
                'status' => 'published',
                'views' => 650,
            ],
            [
                'title' => 'Mengenal Vaksin Halal dan Vaksin Haram',
                'slug' => 'mengenal-vaksin-halal-dan-vaksin-haram',
                'excerpt' => 'Penjelasan tentang komponen vaksin dan status halalnya menurut pandangan Islam.',
                'content' => '<h2>Komponen Vaksin</h2><p>Vaksin modern mengandung antigen, adjuvant, pengawet, dan stabilizer untuk menjaga efektivitasnya.</p><h3>Bahan yang Perlu Diperhatikan</h3><ul><li>Albumin manusia atau bovine</li><li>Gelatin dari sumber halal</li><li>Enzim tripsin dari pankreas babi</li><li>Sel-sel dari ginjal monyet</li></ul><h2>Fatwa MUI tentang Vaksin</h2><p>MUI telah mengeluarkan fatwa tentang vaksin COVID-19 yang menyatakan beberapa vaksin halal dan boleh digunakan.</p>',
                'ai_summary' => 'Artikel ini menjelaskan komponen vaksin, bahan yang perlu diperhatikan, dan fatwa MUI terkait status halal vaksin.',
                'image' => 'https://images.tokopedia.net/img/cache/700/VqbcmM/2024/1/7/halal-vaccines.jpg',
                'category' => 'Kesehatan',
                'source' => 'Internal',
                'author' => 'Islamic Medical Expert',
                'is_published' => true,
                'status' => 'published',
                'views' => 1100,
            ],
            [
                'title' => 'Pentingnya Menjaga Asupan Gula dan Natrium Harian',
                'slug' => 'pentingnya-menjaga-asupan-gula-dan-natrium',
                'excerpt' => 'Ketahui batas konsumsi gula dan garam harian untuk mencegah penyakit kronis di masa depan.',
                'content' => '<h2>Bahaya Tersembunyi di Balik Makanan Olahan</h2><p>Gula dan natrium (garam) adalah dua komponen yang paling sering dikonsumsi secara berlebihan tanpa kita sadari. Keduanya sering ditambahkan ke dalam makanan olahan sebagai pengawet dan penambah rasa. Namun, konsumsi jangka panjang yang tidak terkontrol dapat memicu berbagai penyakit tidak menular (PTM) seperti hipertensi, diabetes melitus, dan penyakit jantung.</p><h3>Berapa Batas Aman Konsumsi Harian?</h3><p>Kementerian Kesehatan Republik Indonesia merekomendasikan rumus <strong>G4-G1-L5</strong> untuk asupan harian:</p><ul><li><strong>Gula:</strong> Maksimal 4 sendok makan (50 gram).</li><li><strong>Garam (Natrium):</strong> Maksimal 1 sendok teh (2.000 mg natrium).</li><li><strong>Lemak:</strong> Maksimal 5 sendok makan (67 gram).</li></ul><h3>Tips Mengontrol Asupan dengan Halalytics</h3><p>Aplikasi Halalytics tidak hanya membantu Anda mengecek kehalalan, tetapi juga kesehatan produk. Gunakan fitur <strong>Nutrition Tracker</strong> kami untuk:</p><ul><li><strong>Scan Label Gizi:</strong> Dapatkan peringatan otomatis jika kadar gula atau natrium dalam suatu produk melebihi batas aman.</li><li><strong>Catatan Harian:</strong> Pantau akumulasi konsumsi Anda sepanjang hari melalui grafik yang mudah dipahami.</li><li><strong>Cari Alternatif Lebih Sehat:</strong> Temukan rekomendasi produk serupa dengan kandungan nutrisi yang lebih seimbang.</li></ul><p>Mulailah kebiasaan sehat hari ini dengan lebih teliti membaca label pangan. Sehat itu investasi, dan Halalytics adalah asisten terbaik untuk menjaga investasi tersebut tetap bernilai.',
                'ai_summary' => 'Panduan praktis mengontrol asupan gula dan natrium harian sesuai rekomendasi kesehatan menggunakan fitur tracking Halalytics.',
                'image' => 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?q=80&w=1200',
                'category' => 'Tips Kesehatan',
                'source' => 'Dinas Kesehatan',
                'author' => 'dr. Siti Aminah',
                'is_published' => true,
                'status' => 'published',
                'views' => 840,
            ],
            [
                'title' => 'Panduan Memilih Susu Formula untuk Bayi',
                'slug' => 'panduan-memilih-susu-formula-untuk-bayi',
                'excerpt' => 'Tips memilih susu formula yang aman dan sesuai dengan kebutuhan nutrisi bayi Anda.',
                'content' => '<h2>Jenis Susu Formula</h2><p>Susu formula terdiri dari formula bayi, formula lanjutan, dan formula khusus untuk bayi dengan kondisi tertentu.</p><h3>Kriteria Pemilihan</h3><ul><li>Komposisi nutrisi lengkap</li><li>Label halal MUI</li><li>Tanggal kadaluarsa</li><li>Rekomendasi dokter</li></ul><h2>Merek Terpercaya</h2><p>Pilih merek yang telah terbukti kualitasnya dan memiliki sertifikasi halal dari lembaga yang diakui.</p>',
                'ai_summary' => 'Artikel ini memberikan panduan memilih susu formula untuk bayi, jenis-jenisnya, kriteria pemilihan, dan merek terpercaya.',
                'image' => 'https://images.tokopedia.net/img/cache/700/VqbcmM/2024/1/9/baby-formula-guide.jpg',
                'category' => 'Kesehatan Ibu & Anak',
                'source' => 'Internal',
                'author' => 'Pediatrician',
                'is_published' => true,
                'status' => 'published',
                'views' => 780,
            ],
            [
                'title' => 'Mengenal Gluten dan Dampaknya bagi Kesehatan',
                'slug' => 'mengenal-gluten-dampaknya-bagi-kesehatan',
                'excerpt' => 'Penjelasan tentang gluten, intoleransi gluten, dan alternatif makanan bebas gluten.',
                'content' => '<h2>Apa Itu Gluten?</h2><p>Gluten adalah protein yang terdapat dalam gandum, barley, dan rye yang memberikan tekstur kenyal pada adonan.</p><h3>Intoleransi Gluten</h3><ul><li>Celiac disease - Autoimun</li><li>Sensitivitas gluten non-celiac</li><li>Alergi gandum</li></ul><h2>Alternatif Bebas Gluten</h2><p>Gunakan tepung beras, tepung jagung, tepung almond, atau tepung kentang sebagai pengganti tepung terigu.</p>',
                'ai_summary' => 'Artikel ini menjelaskan tentang gluten, jenis intoleransi, gejala, dan alternatif makanan bebas gluten.',
                'image' => 'https://images.tokopedia.net/img/cache/700/VqbcmM/2024/1/10/gluten-free.jpg',
                'category' => 'Kesehatan',
                'source' => 'Internal',
                'author' => 'Dietitian',
                'is_published' => true,
                'status' => 'published',
                'views' => 920,
            ],
            [
                'title' => 'Panduan Memahami Titik Kritis Kehalalan pada Obat-obatan',
                'slug' => 'titik-kritis-kehalalan-obat',
                'excerpt' => 'Pelajari sumber bahan baku obat yang berpotensi tidak halal dan cara memastikan keamanan konsumsi obat bagi muslim.',
                'content' => '<h2>Mengapa Obat Bisa Menjadi Tidak Halal?</h2><p>Banyak orang mengira bahwa sertifikasi halal hanya berlaku untuk makanan dan minuman. Padahal, industri farmasi sangat kompleks dan seringkali menggunakan bahan baku yang berasal dari sumber yang kritis secara syariat. Obat-obatan, baik itu obat bebas maupun obat resep, dapat mengandung komponen yang berasal dari hewan atau melalui proses kimia yang melibatkan alkohol.</p><h3>Bahan Kritis dalam Industri Farmasi</h3><ul><li><strong>Gelatin:</strong> Digunakan secara luas untuk cangkang kapsul. Sebagian besar gelatin dunia berasal dari babi atau sapi yang tidak disembelih secara syar-i.</li><li><strong>Magnesium Stearat:</strong> Zat pelicin tablet yang bisa berasal dari lemak hewan atau nabati.</li><li><strong>Alkohol (Etanol):</strong> Sering digunakan sebagai pelarut dalam obat sirup. Batas toleransi MUI adalah 0.5% pada produk akhir jika bukan berasal dari industri khamr.</li><li><strong>Enzim dan Hormon:</strong> Beberapa obat hormon atau enzim (seperti insulin lawas) berasal dari organ hewan.</li></ul><h2>Hukum Mengonsumsi Obat dalam Islam</h2><p>Islam memberikan keringanan (rukhsah) dalam kondisi darurat. Jika tidak ada alternatif obat halal dan penyakit tersebut mengancam nyawa, maka obat tersebut boleh dikonsumsi. Namun, seiring dengan kemajuan teknologi, sudah banyak perusahaan farmasi yang memproduksi obat bersertifikat halal.</p><h3>Cara Cek Kehalalan Obat dengan Halalytics</h3><p>Aplikasi Halalytics kini dilengkapi dengan database <strong>OpenFDA</strong> dan integrasi data BPOM. Anda dapat:</p><ul><li><strong>Scan Barcode Obat:</strong> Temukan informasi komposisi dan status kehalalan secara instan.</li><li><strong>Cari Alternatif Halal:</strong> Jika obat yang Anda cari memiliki status syubhat, AI kami akan merekomendasikan obat dengan fungsi serupa yang sudah terverifikasi halal.</li><li><strong>Konsultasi Ahli Gizi/Farmasi:</strong> Tanyakan langsung melalui fitur chat Hilda untuk mendapatkan panduan lebih lanjut.</li></ul><p>Edukasi diri Anda dan keluarga mengenai pentingnya memilih obat yang tidak hanya menyembuhkan secara fisik, tetapi juga memberikan ketenangan secara spiritual. Sehat itu dimulai dari apa yang kita masukkan ke dalam tubuh dengan penuh kesadaran.</p>',
                'ai_summary' => 'Artikel edukasi mendalam mengenai bahan baku kritis pada obat-obatan seperti gelatin dan alkohol, serta panduan memilih obat halal menggunakan fitur database FDA Halalytics.',
                'image' => 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=1200',
                'category' => 'Edukasi Obat',
                'source' => 'Badan POM & MUI',
                'author' => 'Tim Apoteker Halalytics',
                'is_published' => true,
                'status' => 'published',
                'views' => 2100,
            ],
        ];

        foreach ($articles as $article) {
            Article::updateOrCreate(
                ['slug' => $article['slug']],
                $article
            );
        }
    }
}