@extends('admin.layouts.admin_layout')

@section('title', 'Manajemen Data BPOM')
@section('breadcrumb-parent', 'Data Management')
@section('breadcrumb-current', 'BPOM Data')

@section('content')
<div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4 mb-6">
    <div class="rounded-xl p-4 bg-cyan-500 text-white">
        <div class="text-sm opacity-80">Total Produk</div>
        <div class="text-2xl font-extrabold">{{ number_format($stats['total']) }}</div>
    </div>
    <div class="rounded-xl p-4 bg-emerald-500 text-white">
        <div class="text-sm opacity-80">Terverifikasi</div>
        <div class="text-2xl font-extrabold">{{ number_format($stats['verified']) }}</div>
    </div>
    <div class="rounded-xl p-4 bg-indigo-500 text-white">
        <div class="text-sm opacity-80">Generated by AI</div>
        <div class="text-2xl font-extrabold">{{ number_format($stats['ai_generated']) }}</div>
    </div>
    <div class="rounded-xl p-4 bg-rose-500 text-white">
        <div class="text-sm opacity-80">Potensi Bahaya</div>
        <div class="text-2xl font-extrabold">{{ number_format($stats['dangerous']) }}</div>
    </div>
</div>

<div class="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm p-4 mb-6">
    <form action="{{ route('admin.bpom.index') }}" method="GET" class="grid grid-cols-1 md:grid-cols-12 gap-3">
        <div class="md:col-span-5">
            <input type="text" name="search" class="w-full rounded-lg border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800" placeholder="Cari nama produk, merk, nomor registrasi..." value="{{ request('search') }}">
        </div>
        <div class="md:col-span-3">
            <select name="kategori" class="w-full rounded-lg border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800">
                <option value="">Semua Kategori</option>
                <option value="obat" {{ request('kategori') == 'obat' ? 'selected' : '' }}>Obat</option>
                <option value="kosmetik" {{ request('kategori') == 'kosmetik' ? 'selected' : '' }}>Kosmetik</option>
                <option value="pangan" {{ request('kategori') == 'pangan' ? 'selected' : '' }}>Pangan Olahan</option>
                <option value="suplemen" {{ request('kategori') == 'suplemen' ? 'selected' : '' }}>Suplemen</option>
            </select>
        </div>
        <div class="md:col-span-2">
            <select name="status" class="w-full rounded-lg border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800">
                <option value="">Semua Status</option>
                <option value="aman" {{ request('status') == 'aman' ? 'selected' : '' }}>Aman</option>
                <option value="waspada" {{ request('status') == 'waspada' ? 'selected' : '' }}>Waspada</option>
                <option value="bahaya" {{ request('status') == 'bahaya' ? 'selected' : '' }}>Bahaya</option>
            </select>
        </div>
        <div class="md:col-span-2">
            <button type="submit" class="w-full h-full px-4 py-2 rounded-lg bg-primary text-white font-semibold hover:bg-primary-dark">Cari</button>
        </div>
    </form>
</div>

<div class="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden">
    <div class="overflow-x-auto">
        <table class="w-full text-left">
            <thead>
                <tr class="bg-slate-50 dark:bg-slate-800/30 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                    <th class="px-5 py-4">No. Registrasi</th>
                    <th class="px-5 py-4">Nama Produk</th>
                    <th class="px-5 py-4">Kategori</th>
                    <th class="px-5 py-4">Merk</th>
                    <th class="px-5 py-4">Status</th>
                    <th class="px-5 py-4">Sumber</th>
                    <th class="px-5 py-4 text-right">Aksi</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-slate-100 dark:divide-slate-800">
                @forelse($bpom_data as $data)
                <tr class="hover:bg-slate-50 dark:hover:bg-slate-800/30">
                    <td class="px-5 py-4 text-xs font-mono font-semibold text-slate-700 dark:text-slate-300">{{ $data->nomor_reg }}</td>
                    <td class="px-5 py-4 text-sm text-slate-700 dark:text-slate-300">{{ $data->nama_produk }}</td>
                    <td class="px-5 py-4 text-xs">
                        <span class="inline-flex px-2 py-1 rounded-md bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 font-semibold">{{ strtoupper($data->kategori) }}</span>
                    </td>
                    <td class="px-5 py-4 text-sm text-slate-600 dark:text-slate-400">{{ $data->merk ?: '-' }}</td>
                    <td class="px-5 py-4">
                        @if($data->status_keamanan == 'aman')
                            <span class="inline-flex px-2 py-1 rounded-full text-[11px] font-bold bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600">AMAN</span>
                        @elseif($data->status_keamanan == 'waspada')
                            <span class="inline-flex px-2 py-1 rounded-full text-[11px] font-bold bg-amber-100 dark:bg-amber-900/30 text-amber-600">WASPADA</span>
                        @else
                            <span class="inline-flex px-2 py-1 rounded-full text-[11px] font-bold bg-red-100 dark:bg-red-900/30 text-red-600">BAHAYA</span>
                        @endif
                    </td>
                    <td class="px-5 py-4 text-xs font-semibold">
                        @if($data->sumber_data == 'ai')
                            <span class="inline-flex px-2 py-1 rounded-md bg-indigo-100 dark:bg-indigo-900/30 text-indigo-600">AI</span>
                        @else
                            <span class="inline-flex px-2 py-1 rounded-md bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300">SISTEM</span>
                        @endif
                    </td>
                    <td class="px-5 py-4">
                        <div class="flex justify-end gap-2">
                            <a href="{{ route('admin.bpom.show', $data->id) }}" class="p-2 rounded-lg text-slate-500 hover:text-primary hover:bg-slate-100 dark:hover:bg-slate-800" title="Detail">
                                <span class="material-icons-round text-lg">visibility</span>
                            </a>
                            @if($data->verification_status != 'verified')
                            <form action="{{ route('admin.bpom.verify', $data->id) }}" method="POST" class="inline">
                                @csrf
                                <button class="p-2 rounded-lg text-slate-500 hover:text-emerald-600 hover:bg-emerald-50 dark:hover:bg-emerald-900/20" onclick="return confirm('Verifikasi produk ini?')" title="Verifikasi">
                                    <span class="material-icons-round text-lg">verified</span>
                                </button>
                            </form>
                            @endif
                            <form action="{{ route('admin.bpom.destroy', $data->id) }}" method="POST" class="inline">
                                @csrf
                                @method('DELETE')
                                <button class="p-2 rounded-lg text-slate-500 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20" onclick="return confirm('Hapus data ini?')" title="Hapus">
                                    <span class="material-icons-round text-lg">delete</span>
                                </button>
                            </form>
                        </div>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="7" class="px-5 py-16 text-center">
                        <div class="text-slate-400 text-sm">Data BPOM belum tersedia. Tambahkan data atau sync dari sumber eksternal.</div>
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
    <div class="px-5 py-4 border-t border-slate-100 dark:border-slate-800">{{ $bpom_data->links() }}</div>
</div>
@endsection

@push('scripts')
<script>
    setInterval(() => {
        window.location.reload();
    }, 60000);
</script>
@endpush
