@extends('admin.master')

@section('title', 'BPOM Master Data - Halalytics Admin')

@section('breadcrumb')
<span class="text-slate-400">Data Management</span>
<span class="material-icons-round text-slate-300 text-sm">chevron_right</span>
<span class="font-semibold text-slate-700 dark:text-slate-200">BPOM Data</span>
@endsection

@section('content')
<div class="space-y-6">
    <!-- Quick Metrics Grid -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <div class="bg-white dark:bg-slate-900 rounded-3xl p-6 border border-slate-200 dark:border-slate-800 shadow-sm relative overflow-hidden">
            <div class="absolute top-0 right-0 p-4 opacity-10">
                <span class="material-icons-round text-5xl text-primary">inventory_2</span>
            </div>
            <p class="text-[10px] font-bold uppercase tracking-widest text-slate-400">Total Catalog</p>
            <div class="mt-4">
                <h3 class="text-3xl font-extrabold text-slate-900 dark:text-white">{{ number_format($stats['total']) }}</h3>
                <p class="text-xs text-slate-500 mt-1">Verified products</p>
            </div>
        </div>
        <div class="bg-white dark:bg-slate-900 rounded-3xl p-6 border border-slate-200 dark:border-slate-800 shadow-sm relative overflow-hidden">
            <div class="absolute top-0 right-0 p-4 opacity-10">
                <span class="material-icons-round text-5xl text-emerald-500">verified</span>
            </div>
            <p class="text-[10px] font-bold uppercase tracking-widest text-slate-400">Verified</p>
            <div class="mt-4">
                <h3 class="text-3xl font-extrabold text-slate-900 dark:text-white">{{ number_format($stats['verified']) }}</h3>
                <p class="text-xs text-emerald-600 mt-1">Ready for users</p>
            </div>
        </div>
        <div class="bg-white dark:bg-slate-900 rounded-3xl p-6 border border-slate-200 dark:border-slate-800 shadow-sm relative overflow-hidden">
            <div class="absolute top-0 right-0 p-4 opacity-10">
                <span class="material-icons-round text-5xl text-primary">psychology</span>
            </div>
            <p class="text-[10px] font-bold uppercase tracking-widest text-slate-400">AI Analyzed</p>
            <div class="mt-4">
                <h3 class="text-3xl font-extrabold text-slate-900 dark:text-white">{{ number_format($stats['ai_generated']) }}</h3>
                <p class="text-xs text-slate-500 mt-1">Generated by engine</p>
            </div>
        </div>
        <div class="bg-white dark:bg-slate-900 rounded-3xl p-6 border border-slate-200 dark:border-slate-800 shadow-sm relative overflow-hidden">
            <div class="absolute top-0 right-0 p-4 opacity-10">
                <span class="material-icons-round text-5xl text-rose-500">report_problem</span>
            </div>
            <p class="text-[10px] font-bold uppercase tracking-widest text-slate-400">Potential Risk</p>
            <div class="mt-4">
                <h3 class="text-3xl font-extrabold text-slate-900 dark:text-white">{{ number_format($stats['dangerous']) }}</h3>
                <p class="text-xs text-rose-600 mt-1">Require warning</p>
            </div>
        </div>
    </div>

    <!-- Header Actions -->
    <div class="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
        <div>
            <h2 class="text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight">BPOM Management</h2>
            <p class="text-sm text-slate-500 dark:text-slate-400 mt-1">Central repository for verified product data and safety analysis.</p>
        </div>
        <form action="{{ route('admin.bpom.sync') }}" method="POST" onsubmit="return handleSyncSubmit(this)">
            @csrf
            <button type="submit" id="syncBtn" class="inline-flex items-center gap-3 px-6 py-3.5 bg-primary text-white rounded-2xl font-bold hover:bg-primary-dark transition-all shadow-lg shadow-primary/20 group">
                <span class="material-icons-round text-lg group-hover:rotate-180 transition-transform duration-500">cloud_sync</span>
                <span id="syncText">SYNC EXTERNAL DATA</span>
            </button>
        </form>
    </div>

    <!-- Filter Section -->
    <div class="bg-white dark:bg-slate-900 rounded-3xl p-5 border border-slate-200 dark:border-slate-800 shadow-sm">
        <form action="{{ route('admin.bpom.index') }}" method="GET" class="grid grid-cols-1 md:grid-cols-12 gap-4">
            <div class="md:col-span-5 relative">
                <span class="material-icons-round absolute left-4 top-1/2 -translate-y-1/2 text-slate-400">search</span>
                <input type="text" name="search" class="w-full rounded-2xl border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 pl-12 pr-4 py-3.5 text-sm focus:ring-2 focus:ring-primary" placeholder="Search product name, brand, or reg number..." value="{{ request('search') }}">
            </div>
            <div class="md:col-span-3">
                <select name="kategori" class="w-full rounded-2xl border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 px-4 py-3.5 text-sm focus:ring-2 focus:ring-primary">
                    <option value="">All Categories</option>
                    <option value="obat" {{ request('kategori') == 'obat' ? 'selected' : '' }}>Medicine</option>
                    <option value="kosmetik" {{ request('kategori') == 'kosmetik' ? 'selected' : '' }}>Cosmetic</option>
                    <option value="pangan" {{ request('kategori') == 'pangan' ? 'selected' : '' }}>Food & Beverage</option>
                    <option value="suplemen" {{ request('kategori') == 'suplemen' ? 'selected' : '' }}>Supplement</option>
                </select>
            </div>
            <div class="md:col-span-2">
                <select name="status" class="w-full rounded-2xl border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 px-4 py-3.5 text-sm focus:ring-2 focus:ring-primary">
                    <option value="">All Status</option>
                    <option value="aman" {{ request('status') == 'aman' ? 'selected' : '' }}>Safe</option>
                    <option value="waspada" {{ request('status') == 'waspada' ? 'selected' : '' }}>Warning</option>
                    <option value="bahaya" {{ request('status') == 'bahaya' ? 'selected' : '' }}>Dangerous</option>
                </select>
            </div>
            <div class="md:col-span-2">
                <button type="submit" class="w-full h-full px-4 py-3.5 rounded-2xl bg-slate-900 dark:bg-white dark:text-slate-900 text-white font-bold hover:opacity-90 transition-all">APPLY</button>
            </div>
        </form>
    </div>

    <!-- Data Table -->
    <div class="bg-white dark:bg-slate-900 rounded-[2.5rem] border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden">
        <div class="overflow-x-auto">
            <table class="w-full text-left">
                <thead>
                    <tr class="bg-slate-50 dark:bg-slate-800/50 text-[10px] font-bold text-slate-400 uppercase tracking-widest">
                        <th class="px-6 py-5">Product Entity</th>
                        <th class="px-6 py-5">Classification</th>
                        <th class="px-6 py-5">Manufacturer</th>
                        <th class="px-6 py-5">Safety Index</th>
                        <th class="px-6 py-5">Source</th>
                        <th class="px-6 py-5 text-right">Actions</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-100 dark:divide-slate-800">
                    @forelse($bpom_data as $data)
                    <tr class="group hover:bg-slate-50/50 dark:hover:bg-slate-800/30 transition-all">
                        <td class="px-6 py-6">
                            <div class="flex items-center gap-4">
                                <div class="w-14 h-14 rounded-2xl bg-white dark:bg-slate-800 flex-shrink-0 overflow-hidden flex items-center justify-center border border-slate-100 dark:border-slate-700 shadow-sm group-hover:scale-105 transition-transform">
                                    <img src="{{ $data->image_url }}" alt="{{ $data->nama_produk }}" class="w-full h-full object-cover" onerror="this.onerror=null; this.src='/images/placeholders/product-placeholder.svg';">
                                </div>
                                <div>
                                    <div class="text-sm font-extrabold text-slate-900 dark:text-white">{{ Str::limit($data->nama_produk, 35) }}</div>
                                    @if($data->nomor_reg)
                                    <div class="flex items-center mt-1">
                                        <span class="px-1.5 py-0.5 rounded bg-slate-100 dark:bg-slate-800 text-[9px] font-mono font-bold text-slate-500 uppercase">{{ $data->nomor_reg }}</span>
                                    </div>
                                    @endif
                                </div>
                            </div>
                        </td>
                        <td class="px-6 py-6">
                            <span class="inline-flex px-3 py-1 rounded-full bg-slate-100 dark:bg-slate-800 text-[10px] font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider border border-slate-200/50 dark:border-slate-700/50">
                                {{ $data->kategori }}
                            </span>
                        </td>
                        <td class="px-6 py-6">
                            <div class="text-xs font-semibold text-slate-600 dark:text-slate-400">{{ $data->merk ?: 'N/A' }}</div>
                            <div class="text-[10px] text-slate-400 truncate max-w-[150px] mt-1">{{ $data->pendaftar ?: 'No pendaftar data' }}</div>
                        </td>
                        <td class="px-6 py-6">
                            @if($data->status_keamanan == 'aman')
                                <div class="flex items-center gap-2">
                                    <div class="h-2 w-2 rounded-full bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.5)]"></div>
                                    <span class="text-[10px] font-bold text-emerald-600 uppercase tracking-widest">SAFE</span>
                                </div>
                            @elseif($data->status_keamanan == 'waspada')
                                <div class="flex items-center gap-2">
                                    <div class="h-2 w-2 rounded-full bg-amber-500 shadow-[0_0_8px_rgba(245,158,11,0.5)]"></div>
                                    <span class="text-[10px] font-bold text-amber-600 uppercase tracking-widest">WARNING</span>
                                </div>
                            @else
                                <div class="flex items-center gap-2">
                                    <div class="h-2 w-2 rounded-full bg-rose-500 shadow-[0_0_8px_rgba(239,68,68,0.5)]"></div>
                                    <span class="text-[10px] font-bold text-rose-600 uppercase tracking-widest">DANGER</span>
                                </div>
                            @endif
                        </td>
                        <td class="px-6 py-6">
                            @php
                                $sourceLabels = [
                                    'ai' => ['label' => 'AI ENGINE', 'color' => 'bg-primary/10 text-primary border-primary/20'],
                                    'open_food_facts' => ['label' => 'OPEN FOOD', 'color' => 'bg-emerald-50 dark:bg-emerald-900/20 text-emerald-600 border-emerald-100'],
                                    'open_beauty_facts' => ['label' => 'OPEN BEAUTY', 'color' => 'bg-sky-50 dark:bg-sky-900/20 text-sky-600 border-sky-100'],
                                    'user_contribution' => ['label' => 'CONTRIBUTOR', 'color' => 'bg-amber-50 dark:bg-amber-900/20 text-amber-600 border-amber-100'],
                                ];
                                $source = $sourceLabels[$data->sumber_data] ?? ['label' => 'SYSTEM', 'color' => 'bg-slate-100 dark:bg-slate-800 text-slate-500 border-slate-200'];
                            @endphp
                            <span class="inline-flex px-2 py-0.5 rounded border {{ $source['color'] }} text-[9px] font-extrabold uppercase tracking-widest">
                                {{ $source['label'] }}
                            </span>
                        </td>
                        <td class="px-6 py-6 text-right">
                            <div class="flex justify-end gap-1">
                                <a href="{{ route('admin.bpom.show', $data->id) }}" class="h-9 w-9 rounded-xl flex items-center justify-center text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 hover:text-primary transition-all">
                                    <span class="material-icons-round text-lg">visibility</span>
                                </a>
                                @if($data->verification_status != 'verified')
                                <form action="{{ route('admin.bpom.verify', $data->id) }}" method="POST" class="inline">
                                    @csrf
                                    <button class="h-9 w-9 rounded-xl flex items-center justify-center text-slate-400 hover:bg-emerald-50 dark:hover:bg-emerald-900/20 hover:text-emerald-600 transition-all" onclick="return confirm('Verify this product data?')">
                                        <span class="material-icons-round text-lg">verified</span>
                                    </button>
                                </form>
                                @endif
                                <form action="{{ route('admin.bpom.destroy', $data->id) }}" method="POST" class="inline">
                                    @csrf
                                    @method('DELETE')
                                    <button class="h-9 w-9 rounded-xl flex items-center justify-center text-slate-400 hover:bg-rose-50 dark:hover:bg-rose-900/20 hover:text-rose-500 transition-all" onclick="return confirm('Remove this data record?')">
                                        <span class="material-icons-round text-lg">delete_outline</span>
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="6" class="px-6 py-20 text-center">
                            <div class="flex flex-col items-center">
                                <div class="h-20 w-20 rounded-full bg-slate-50 dark:bg-slate-800/50 flex items-center justify-center mb-4">
                                    <span class="material-icons-round text-4xl text-slate-300">cloud_off</span>
                                </div>
                                <h4 class="text-xl font-bold text-slate-800 dark:text-white">Master Data Empty</h4>
                                <p class="text-sm text-slate-400 mt-2 max-w-sm mx-auto">No records found matching your criteria. Use the sync feature to import external catalog data.</p>
                            </div>
                        </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        <div class="px-8 py-6 bg-slate-50/30 dark:bg-slate-800/20 border-t border-slate-100 dark:border-slate-800">
            {{ $bpom_data->links() }}
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
function handleSyncSubmit(form) {
    const btn = document.getElementById('syncBtn');
    const text = document.getElementById('syncText');
    const icon = btn.querySelector('.material-icons-round');
    
    btn.disabled = true;
    btn.classList.add('opacity-50', 'cursor-not-allowed');
    text.innerText = 'SYNCING DATA...';
    icon.classList.add('animate-spin');
    
    return true;
}
</script>
@endpush

