@extends('admin.layouts.admin_layout')

@section('title', 'Manajemen Data BPOM')
@section('breadcrumb-parent', 'Data Management')
@section('breadcrumb-current', 'BPOM Data')

@section('content')
<div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4 mb-6">
    <div class="metric-card metric-card--primary">
        <div class="text-sm opacity-80">Total Produk</div>
        <div class="text-2xl font-extrabold">{{ number_format($stats['total']) }}</div>
    </div>
    <div class="metric-card metric-card--accent">
        <div class="text-sm opacity-80">Terverifikasi</div>
        <div class="text-2xl font-extrabold">{{ number_format($stats['verified']) }}</div>
    </div>
    <div class="metric-card metric-card--soft">
        <div class="text-sm opacity-80">Generated by AI</div>
        <div class="text-2xl font-extrabold">{{ number_format($stats['ai_generated']) }}</div>
    </div>
    <div class="metric-card metric-card--danger">
        <div class="text-sm opacity-80">Potensi Bahaya</div>
        <div class="text-2xl font-extrabold">{{ number_format($stats['dangerous']) }}</div>
    </div>
</div>

<!-- Sync External Data Button -->
<div class="flex items-center justify-between mb-6">
    <div>
        <h2 class="text-2xl font-extrabold text-slate-800 dark:text-white tracking-tight">BPOM Data Management</h2>
        <p class="text-slate-500 text-sm mt-1">Kelola dan verifikasi data produk dari berbagai sumber.</p>
    </div>
    <form action="{{ route('admin.bpom.sync') }}" method="POST" onsubmit="this.querySelector('button').disabled=true; this.querySelector('button span:last-child').textContent='Syncing...';">
        @csrf
        <button type="submit" class="inline-flex items-center gap-2 px-4 py-2 bg-primary text-white rounded-lg font-semibold hover:bg-primary-dark transition shadow-lg shadow-primary/20 dark:shadow-none">
            <span class="material-icons-round text-lg">cloud_sync</span>
            <span>Sync Data Eksternal</span>
        </button>
    </form>
</div>

<div class="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm p-4 mb-6">
    <form action="{{ route('admin.bpom.index') }}" method="GET" class="grid grid-cols-1 md:grid-cols-12 gap-3">
        <div class="md:col-span-5">
            <input type="text" name="search" class="w-full rounded-lg border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800" placeholder="Cari nama produk, merk, nomor registrasi..." value="{{ request('search') }}">
        </div>
        <div class="md:col-span-3">
            <select name="kategori" class="w-full rounded-lg border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800">
                <option value="">Semua Kategori</option>
                <option value="obat" {{ request('kategori') == 'obat' ? 'selected' : '' }}>Obat</option>
                <option value="kosmetik" {{ request('kategori') == 'kosmetik' ? 'selected' : '' }}>Kosmetik</option>
                <option value="pangan" {{ request('kategori') == 'pangan' ? 'selected' : '' }}>Pangan Olahan</option>
                <option value="suplemen" {{ request('kategori') == 'suplemen' ? 'selected' : '' }}>Suplemen</option>
            </select>
        </div>
        <div class="md:col-span-2">
            <select name="status" class="w-full rounded-lg border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800">
                <option value="">Semua Status</option>
                <option value="aman" {{ request('status') == 'aman' ? 'selected' : '' }}>Aman</option>
                <option value="waspada" {{ request('status') == 'waspada' ? 'selected' : '' }}>Waspada</option>
                <option value="bahaya" {{ request('status') == 'bahaya' ? 'selected' : '' }}>Bahaya</option>
            </select>
        </div>
        <div class="md:col-span-2">
            <button type="submit" class="w-full h-full px-4 py-2 rounded-lg bg-primary text-white font-semibold hover:bg-primary-dark">Cari</button>
        </div>
    </form>
</div>

<div class="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden">
    <div class="overflow-x-auto">
        <table class="w-full text-left">
            <thead>
                <tr class="bg-slate-50 dark:bg-slate-800/30 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                    <th class="px-5 py-4">Produk</th>
                    <th class="px-5 py-4">Kategori</th>
                    <th class="px-5 py-4">Merk</th>
                    <th class="px-5 py-4">Status</th>
                    <th class="px-5 py-4">Sumber</th>
                    <th class="px-5 py-4 text-right">Aksi</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-slate-100 dark:divide-slate-800">
                @forelse($bpom_data as $data)
                <tr class="hover:bg-slate-50 dark:hover:bg-slate-800/30">
                    <td class="px-5 py-4">
                        <div class="flex items-center gap-3">
                            <div class="w-10 h-10 rounded-lg bg-primary/10 flex-shrink-0 overflow-hidden flex items-center justify-center border border-slate-100 dark:border-slate-700">
                                @php
                                    $imgSrc = $data->image_url;
                                    if (!$imgSrc || str_contains($imgSrc, 'placeholder.svg')) {
                                        $imgSrc = 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?q=80&w=150'; // Default BPOM/Product image
                                    }
                                @endphp
                                <img src="{{ $imgSrc }}" alt="{{ $data->nama_produk }}" class="w-full h-full object-cover" onerror="this.onerror=null; this.src='https://ui-avatars.com/api/?name='+encodeURIComponent('{{ $data->nama_produk }}')+'&background=random';">
                            </div>
                            <div>
                                <div class="text-sm font-bold text-slate-800 dark:text-white">{{ Str::limit($data->nama_produk, 40) }}</div>
                                @if($data->nomor_reg)
                                <div class="text-[11px] text-slate-400 font-mono">{{ $data->nomor_reg }}</div>
                                @endif
                            </div>
                        </div>
                    </td>
                    <td class="px-5 py-4 text-xs">
                        <span class="inline-flex px-2 py-1 rounded-md bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 font-semibold">{{ strtoupper($data->kategori) }}</span>
                    </td>
                    <td class="px-5 py-4 text-sm text-slate-600 dark:text-slate-400">{{ $data->merk ?: '-' }}</td>
                    <td class="px-5 py-4">
                        @if($data->status_keamanan == 'aman')
                            <span class="inline-flex px-2 py-1 rounded-full text-[11px] font-bold bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600">AMAN</span>
                        @elseif($data->status_keamanan == 'waspada')
                            <span class="inline-flex px-2 py-1 rounded-full text-[11px] font-bold bg-amber-100 dark:bg-amber-900/30 text-amber-600">WASPADA</span>
                        @else
                            <span class="inline-flex px-2 py-1 rounded-full text-[11px] font-bold bg-red-100 dark:bg-red-900/30 text-red-600">BAHAYA</span>
                        @endif
                    </td>
                    <td class="px-5 py-4 text-xs font-semibold">
                        @if($data->sumber_data == 'ai')
                            <span class="inline-flex px-2 py-1 rounded-md bg-primary/10 text-primary">AI</span>
                        @elseif($data->sumber_data == 'open_food_facts')
                            <span class="inline-flex px-2 py-1 rounded-md bg-emerald-50 text-emerald-600 border border-emerald-100">OFF</span>
                        @elseif($data->sumber_data == 'open_beauty_facts')
                            <span class="inline-flex px-2 py-1 rounded-md bg-primary/10 text-primary border border-primary/20">OBF</span>
                        @elseif($data->sumber_data == 'user_contribution')
                            <span class="inline-flex px-2 py-1 rounded-md bg-sky-50 text-sky-600 border border-sky-100">USER</span>
                        @else
                            <span class="inline-flex px-2 py-1 rounded-md bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300">SISTEM</span>
                        @endif
                    </td>
                    <td class="px-5 py-4">
                        <div class="flex justify-end gap-2">
                            <a href="{{ route('admin.bpom.show', $data->id) }}" class="p-2 rounded-lg text-slate-500 hover:text-primary hover:bg-slate-100 dark:hover:bg-slate-800" title="Detail">
                                <span class="material-icons-round text-lg">visibility</span>
                            </a>
                            @if($data->verification_status != 'verified')
                            <form action="{{ route('admin.bpom.verify', $data->id) }}" method="POST" class="inline">
                                @csrf
                                <button class="p-2 rounded-lg text-slate-500 hover:text-emerald-600 hover:bg-emerald-50 dark:hover:bg-emerald-900/20" onclick="return confirm('Verifikasi produk ini?')" title="Verifikasi">
                                    <span class="material-icons-round text-lg">verified</span>
                                </button>
                            </form>
                            @endif
                            <form action="{{ route('admin.bpom.destroy', $data->id) }}" method="POST" class="inline">
                                @csrf
                                @method('DELETE')
                                <button class="p-2 rounded-lg text-slate-500 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20" onclick="return confirm('Hapus data ini?')" title="Hapus">
                                    <span class="material-icons-round text-lg">delete</span>
                                </button>
                            </form>
                        </div>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="6" class="px-5 py-16 text-center">
                        <div class="text-slate-400 text-sm">
                            <span class="material-icons-round text-4xl mb-2 block">cloud_sync</span>
                            Data BPOM belum tersedia. Klik <strong>Sync Data Eksternal</strong> untuk mengambil data dari OpenFoodFacts dan OpenBeautyFacts.
                        </div>
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
    <div class="px-5 py-4 border-t border-slate-100 dark:border-slate-800">{{ $bpom_data->links() }}</div>
</div>
@endsection
